name: gallagher prod

on:
  push:
  pull_request:
    branches: [ "prod" ]
  workflow_dispatch:

env:
  #ARM_CLIENT_ID: '${{ sectets.AzureID}}'
  TF_ENV: 'prod'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Security Scans (whitesource)
        run: echo whitesource

      - name: code linter
        run: echo linter

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: echo plan

      - name: Terraform apply
        run: echo apply

      - name: unit tests
        run: echo tests